<a href="https://colab.research.google.com/github/amitraj360/Machine-Learning-TA-/blob/main/TutLab1_Q1(a).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CS 403/ CS 603, Machine Learning


Lab: 08-01-2021


Closed form Linear Regression

In [ ]:
import matplotlib.pyplot as plt 
plt.style.use('ggplot')
%matplotlib inline

In [ ]:
import numpy as np
import pandas as pd  
import seaborn as sns 
plt.rcParams['figure.figsize'] = (12, 8)

In [ ]:
X = np.array([[2104, 5],[1416, 3],[1534, 3]], dtype=np.float64)
X

array([[2104.,    5.],
       [1416.,    3.],
       [1534.,    3.]])

In [ ]:
y = np.array([460, 232, 315], dtype=np.float64)

In [ ]:
y.shape #it should print (3,) but not printing 

(3,)

In [ ]:
y = y[:,np.newaxis] ##increses dimension by one mean one dimension will become 2d so on

In [ ]:
y.shape

(3, 1)

In [ ]:
print(np.shape(X))

(3, 2)


In [ ]:
X

array([[2104.,    5.],
       [1416.,    3.],
       [1534.,    3.]])

In [ ]:
# ones = np.ones((X.shape[0], 1)) #return a array with size filled with ones
# X
# X = np.hstack((ones, X)) # function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

In [ ]:
print(X)

[[2104.    5.]
 [1416.    3.]
 [1534.    3.]]


In [ ]:
print(X.shape)
X

(3, 2)


array([[2104.,    5.],
       [1416.,    3.],
       [1534.,    3.]])

Ypredict = X.Theta

In [ ]:
def Ypredict(X, theta):
  return np.dot(X, theta)

# Closed Form

Getting the theta

In [ ]:
def closedfrom(X,Y):
  Y = np.mat(Y)
  theta_1 = np.dot(X.T, X)
  theta_2 = np.dot(X.T, y)

  #If our matrix is not invertible we can use pseudo inverse.(Question 2)
 
  theta = np.linalg.inv(theta_1).dot(theta_2)  #inverse of matrix and multiplication

  #theta = np.linalg.pinv(theta_1).dot(theta_2) 
  return theta

In [ ]:
theta = closedfrom(X, y)
print(theta)

[[ 0.07189298]
 [59.26588166]]


In [ ]:
print(X.shape)
print(X)
y_predict =Ypredict(X,theta)
y_predict

(3, 2)
[[2104.    5.]
 [1416.    3.]
 [1534.    3.]]


array([[447.59224539],
       [279.59810949],
       [288.08148153]])

In [ ]:
error = y-y_predict
error

array([[ 12.40775461],
       [-47.59810949],
       [ 26.91851847]])